backend:
  name: github
  repo: House-of-Olympus-Apparel/-house-of-olympus-website
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "data/products"
    create: true
    slug: "{{fields.name}}"
    fields:
      - label: "Name"
        name: "name"
        widget: "string"

      - label: "Price"
        name: "price"
        widget: "number"

      - label: "Quantity"
        name: "quantity"
        widget: "number"
        value_type: "int"
        min: 0
        default: 1

      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - "Women's New"
          - "Men's New"
          - "Activewear"
          - "Women's Premium"
          - "Men's Premium"
          - "Thrifted Women's"
          - "Thrifted Men's"
          - "Handbags"
          - "Footwear"
          - "Accessories"
          - "Home & More"

      - label: "Description"
        name: "description"
        widget: "text"

      - label: "Image"
        name: "image"
        widget: "image"
        required: false
      - label: "Stripe Payment Link"
        name: "payment_link"
        widget: "string"
        required: false
      - label: "Status"
        name: "status"
        widget: "string"
        default: "Available"
