backend:
  name: github
  repo: House-of-Olympus-Apparel/-house-of-olympus-website
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "data/products"
    create: true
    slug: "{{fields.name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image", required: false }
